import Link from 'next/link';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: '1minyt — Privacy Policy',
  description:
    'How 1minyt handles your YouTube data, OAuth tokens, and AI summaries.',
};

export default function PrivacyPolicy() {
  return (
    <main style={{ padding: '48px 24px', maxWidth: 760, margin: '0 auto' }}>
      <h1
        style={{
          fontSize: 32,
          fontWeight: 800,
          letterSpacing: '-0.02em',
          marginBottom: 8,
        }}
      >
        Privacy Policy
      </h1>
      <p style={{ color: '#8b8b94', fontSize: 13, marginBottom: 32 }}>
        Last updated: August 2, 2026
      </p>

      <Prose>
        <p>
          1minyt (&quot;we&quot;, &quot;us&quot;, or &quot;our&quot;) is a
          self-hosted tool that connects to your YouTube account to organize,
          search, and summarize your subscriptions. This Privacy Policy explains
          what information we collect, how we use it, and your rights.
        </p>

        <h2>Your data, your account</h2>
        <p>
          1minyt connects to YouTube via OAuth 2.0. We never see or store your
          Google password. The OAuth tokens we receive are scoped to read your
          subscriptions, playlists, and (where you enable it) video transcripts.
          These tokens are stored encrypted in your own database and are never
          shared with third parties. You can revoke access or delete your
          account at any time from the Settings page.
        </p>

        <h2>What we collect</h2>
        <p>We collect only what is necessary to provide the service:</p>
        <ul>
          <li>
            <strong>OAuth tokens</strong> — to sync your YouTube data on your
            behalf.
          </li>
          <li>
            <strong>Subscription and metadata</strong> — channel names,
            thumbnails, video titles, descriptions, and publish times that you
            have explicitly authorized us to read.
          </li>
          <li>
            <strong>Transcripts and summaries</strong> — video captions fetched
            on demand, plus AI-generated summaries and chat responses kept
            locally against your account.
          </li>
          <li>
            <strong>Preferences</strong> — folders, tags, and saved items you
            create.
          </li>
        </ul>

        <h2>How we use your data</h2>
        <ul>
          <li>
            To sync, display, and organize your YouTube subscriptions.
          </li>
          <li>
            To generate AI summaries and power transcript search and chat, using
            the AI provider you configure.
          </li>
          <li>
            To surface metrics (e.g., watch counts, topic coverage) derived from
            your own activity.
          </li>
        </ul>

        <h2>Data retention &amp; deletion</h2>
        <p>
          Your data stays in your own database. Removing a channel, clearing a
          summary, or disconnecting your YouTube account removes the related
            data from 1minyt. Full account deletion permanently erases all
          records tied to your account.
        </p>

        <h2>AI providers &amp; Zero Data Retention</h2>
        <p>
          Summaries and chat are generated by large language models you specify
          in your configuration. We route these requests through providers that
          follow Zero Data Retention (ZDR) policies, meaning the only data that
          leaves your account is the content you explicitly request
          summarization or chat for (e.g., a video transcript), and it is not
          retained, logged, or used for training by the provider. No usage data,
          prompts, or responses are stored beyond what is needed to complete the
          request.
        </p>

        <h2>Cookies &amp; analytics</h2>
        <p>
          We do not run advertising or cross-site tracking. If you enable
          analytics in your deployment, it is on your own domain and under your
          control.
        </p>

        <h2>Children</h2>
        <p>
          1minyt is not offered to children under 13, and we do not knowingly
          collect personal information from children.
        </p>

        <h2>Changes to this policy</h2>
        <p>
          We may update this policy. Changes are posted here with an updated
          &quot;Last updated&quot; date.
        </p>

        <h2>Contact</h2>
        <p>
          Questions? Open an issue at the project repository or reach out to the
          maintainer.
        </p>
      </Prose>

      <p style={{ marginTop: 32, fontSize: 13, color: '#8b8b94' }}>
        <Link href="/" style={{ color: '#5b9eff', textDecoration: 'none' }}>
          ← Back to 1minyt
        </Link>
      </p>
    </main>
  );
}

function Prose({ children }: { children: React.ReactNode }) {
  return (
    <div
      style={{
        color: '#c2c2cb',
        lineHeight: 1.7,
        fontSize: 15,
        maxWidth: '68ch',
      }}
    >
      {children}
    </div>
  );
}
